### ISSUE TITLE
Add entity: sensor.solcast_forecast_yesterday

### ISSUE THREAD

**Issue by home409ca** [oziee/ha-solcast-solar#200]
### The problem

Can you add the sensor.solcast_forecast_yesterday entity? What midnight would be rewritten from the sensor.solcast_forecast_today entity?

I would like to see the forecast for yesterday and its implementation on the apex chart, not just today.

![image](https://github.com/oziee/ha-solcast-solar/assets/114701129/c0f1e768-e6b0-4278-a048-0ae692299bce)

### What version of Solcast Integration has the issue?

4.0.7

### Diagnostics information

https://community.home-assistant.io/t/solcast-global-solar-power-forecast-integration/334681/230

### Logs debug/info/error output

```txt
no problem - its future
```

**Comment by oziee** [comment]
nope.. this is a forecast integration not a past integration..

that being said all the data you would need to create a sensor yourself is all there and you can call the service to query for data for any date

```
service: solcast_solar.query_forecast_data
data:
  start_date_time: 2023-09-19T00:00
  end_date_time: 2023-09-19T23:59
```
