### ISSUE TITLE
Recorder include / exclude in installation instructions

### ISSUE THREAD

**Issue by Swallowtail23** [oziee/ha-solcast-solar#26]
Default install instructions say:

> Setup the Recorder to record data.. something like
```
recorder:
  purge_keep_days: 31
  include:
    entity_globs:
      - sensor.solcast*
```
HA installed out of the box does not include a 'recorder:' section in configuration.yaml, and records everything.

From the HA doco (https://www.home-assistant.io/integrations/recorder/#configure-filter):

> Filters are applied as follows:
> 
> No includes or excludes - pass all entities
> Includes, no excludes - only include specified entities

From my reading of the doco following the instructions you provide word for word will result in recorder failing to record anything *but* the solcast entities "Includes, no excludes - only include specified entities".
