### ISSUE TITLE
API calls are reduced by two.

### ISSUE THREAD

**Issue by Rasenkardinal** [oziee/ha-solcast-solar#262]
### The problem

I'm thrilled to have found this integration. The predictions are significantly better than anything I've used before. Now, onto my issue: I've created a script for testing purposes that allows me to manually trigger the update of prediction data. However, each time I do this, TWO of the available TEN API calls are deducted. Is this a known phenomenon? Does anyone have a solution? Thank you very much and sunny regards! 

Here is the simple script in YAML:

```
alias: "Solcast Update "
sequence:
  - service: solcast_solar.update_forecasts
    metadata: {}
    data: {}
    enabled: true
mode: single
icon: mdi:update

```

### What version of Solcast Integration has the issue?

 v4.0.14

### What version of Home Assistant are you using?

2024.3.1

### Logs debug/info/error output

```txt
no error reported;
skript works as intended;
But TWO Calls are used
```
