### ISSUE TITLE
Document how to access hourly values for use in  templates/ automations.

### ISSUE THREAD

**Issue by purcell-lab** [oziee/ha-solcast-solar#28]
Thanks for the work on the Solcast integration, it has been really helpful as I am outside the Forecast Solar regions.

Would it be possible to document how to access the hourly values in the ReadMe, so they can be used in other automations.

I can see that 13.7 kWh is forecast between 1000-1100, but I cannot find this value as an attribute or sensor anywhere?

![image](https://user-images.githubusercontent.com/79175134/154652448-db2914b5-3ce3-47c1-bbed-19aae68bfe8c.png)

![image](https://user-images.githubusercontent.com/79175134/154652686-c6a8c63b-a707-4241-9040-e30589355836.png)

**Comment by oziee** [comment]
Dunno.. the values in the energy graph are handed to HA to display but are not accessible 

The second graph you posted is the total forecast value which changes through the day as the solcast forecast totals adjust with actual history and future forecast data

Would have to change the code to allow for day the current days hourly values to be available 

All the data is in the HA database, so should be available to be retrieved and used but I haven't ever tried

**Comment by purcell-lab** [comment]
For anyone else looking for a solution I ended up using a REST call direct to SolCast.

Would be nice for this integration to expose these values directly:

```yaml
rest:
- resource: https://api.solcast.com.au/rooftop_sites/SITE_ID/forecasts?format=json&api_key=API_KEY&hours=72
  scan_interval: '00:59:00' # RATE LIMIT!
  sensor:
  - name: "Solcast Forecast Data"
    force_update: true
    value_template: "{{ value_json.forecasts[0].pv_estimate|round(2) }}"
    json_attributes:
    - forecasts
  - name: "Solcast Forecast 10"
    force_update: true
    value_template: "{{ value_json.forecasts[0].pv_estimate10|round(2) }}"
  - name: "Solcast Forecast 90"
    force_update: true
    value_template: "{{ value_json.forecasts[0].pv_estimate90|round(2) }}"
```
