### ISSUE TITLE
Today chart don't match with website

### ISSUE THREAD

**Issue by MiguelAngelLV** [oziee/ha-solcast-solar#63]
Sometimes, in the chart of the day don't match with website showing a huge "hole" in random hour.

![image](https://user-images.githubusercontent.com/638110/179400257-1fc32b0b-7f89-4b54-9755-236069c51179.png)

Match with attributes:

```
forecast: 
- period_end: '2022-07-17T00:00:00+02:00'
  pv_estimate: 0
- period_end: '2022-07-17T01:00:00+02:00'
  pv_estimate: 0
- period_end: '2022-07-17T02:00:00+02:00'
  pv_estimate: 0
- period_end: '2022-07-17T03:00:00+02:00'
  pv_estimate: 0
- period_end: '2022-07-17T04:00:00+02:00'
  pv_estimate: 0
- period_end: '2022-07-17T05:00:00+02:00'
  pv_estimate: 0
- period_end: '2022-07-17T06:00:00+02:00'
  pv_estimate: 0
- period_end: '2022-07-17T07:00:00+02:00'
  pv_estimate: 0.048299999999999996
- period_end: '2022-07-17T08:00:00+02:00'
  pv_estimate: 0.63645
- period_end: '2022-07-17T09:00:00+02:00'
  pv_estimate: 1.56455
- period_end: '2022-07-17T10:00:00+02:00'
  pv_estimate: 2.4407
- period_end: '2022-07-17T11:00:00+02:00'
  pv_estimate: 3.0985
- period_end: '2022-07-17T12:00:00+02:00'
  pv_estimate: 3.5501
- period_end: '2022-07-17T13:00:00+02:00'
  pv_estimate: 3.76835
- period_end: '2022-07-17T14:00:00+02:00'
  pv_estimate: 1.8828
- period_end: '2022-07-17T15:00:00+02:00'
  pv_estimate: 3.52965
- period_end: '2022-07-17T16:00:00+02:00'
  pv_estimate: 3.0606
- period_end: '2022-07-17T17:00:00+02:00'
  pv_estimate: 2.3783000000000003
- period_end: '2022-07-17T18:00:00+02:00'
  pv_estimate: 1.48845
- period_end: '2022-07-17T19:00:00+02:00'
  pv_estimate: 0.5969
- period_end: '2022-07-17T20:00:00+02:00'
  pv_estimate: 0.08549999999999999
- period_end: '2022-07-17T21:00:00+02:00'
  pv_estimate: 0.00845
- period_end: '2022-07-17T22:00:00+02:00'
  pv_estimate: 0
- period_end: '2022-07-17T23:00:00+02:00'
  pv_estimate: 0

```
But not with website:

![image](https://user-images.githubusercontent.com/638110/179400416-c8c0227b-280a-4412-93ea-6e2890c01357.png)

```json
[
   {
      "pv_estimate":3.6974,
      "period_end":"2022-07-17T13:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":3.7656,
      "period_end":"2022-07-17T12:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":3.7942,
      "period_end":"2022-07-17T12:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":3.7425,
      "period_end":"2022-07-17T11:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":3.6431,
      "period_end":"2022-07-17T11:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":3.4571,
      "period_end":"2022-07-17T10:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":3.2288,
      "period_end":"2022-07-17T10:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":2.9682,
      "period_end":"2022-07-17T09:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":2.6352,
      "period_end":"2022-07-17T09:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":2.2462,
      "period_end":"2022-07-17T08:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":1.796,
      "period_end":"2022-07-17T08:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":1.3331,
      "period_end":"2022-07-17T07:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0.8536,
      "period_end":"2022-07-17T07:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0.4193,
      "period_end":"2022-07-17T06:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0.077,
      "period_end":"2022-07-17T06:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0.0196,
      "period_end":"2022-07-17T05:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T05:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T04:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T04:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T03:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T03:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T02:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T02:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T01:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T01:00:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T00:30:00.0000000Z",
      "period":"PT30M"
   },
   {
      "pv_estimate":0,
      "period_end":"2022-07-17T00:00:00.0000000Z",
      "period":"PT30M"
   }
]

```
