### ISSUE TITLE
solcast_update_all_forecasts event doesn't poll nay forecast

### ISSUE THREAD

**Issue by kds69** [oziee/ha-solcast-solar#93]
Regardless if via automation or manual, event call "solcast_update_all_forecasts" doesn't poll any data/update
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.4

```
  "integration_manifest": {
    "domain": "solcast_solar",
    "name": "Solcast PV Forecast",
    "version": "3.0.32",
    "config_flow": true,
    "documentation": "https://github.com/oziee/ha-solcast-solar",
    "issue_tracker": "https://github.com/oziee/ha-solcast-solar/issues",
    "requirements": [
      "aiohttp>=3.6.2",
      "datetime>=4.3",
      "isodate>=0.6.0"
    ],
    "dependencies": [],
    "after_dependencies": [
      "http"
    ],
    "iot_class": "cloud_polling",
    "integration_type": "service",
    "codeowners": [
      "@oziee"
    ],
    "is_built_in": false
  },
  "data": {
    "info": {
      "api_key": "**REDACTED**",
      "const_disableautopoll": true
    }
```

```
  - alias: "prévision solcast"
    mode: single
    trigger:
        platform: time_pattern
        hours: "/3"
        minutes: "0"
        seconds: "0"
    # condition:
    #   - condition: sun
    #     before: sunset
    #     after: sunrise
    action:
      - event: solcast_update_all_forecasts
        event_data: {}
```

**Comment by oziee** [comment]
the event is `update_forecasts` (probably was renamed at some stage)

**Comment by peted-davis** [comment]
Similar issue here. This is the automation script I am using, but it isn't triggering anything. I have changed `- event: solcast_update_all_forecasts` to `- event: update_forecasts` as you suggested, but it still doesn't trigger when I manually run the automation

```
alias: Solcast Forecast
description: ""
mode: single
trigger:
  - platform: time_pattern
    hours: /4
condition:
  - condition: sun
    after: sunrise
    before: sunset
action:
  - event: update_forecasts
    event_data: {}
```
